server:
  port: 0
spring:
  application:
    name: task-tracker-email-sender
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: email-sender-group
      properties:
        spring:
          json:
            trusted.packages: com.walking.backend.domain.dto.MessageDto,com.walking.scheduler.domain.dto.MessageDto
            type.mapping: MessageDto:com.walking.emailSender.dto.MessageDto
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
kafka:
  topic-name: EMAIL_SENDING_TASKS