spring:
  application:
    name: task-tracker-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_tracker_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  data:
    redis:
      port: 6379
      host: localhost
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094
      acks: all
security:
  jwt:
    secret: 769783393f00a7684ff30000de89a34a0315b8d48f2450baf01b68850df5bbe1
    access_token_expiration: 30
    refresh_token_expiration: 300
    redis:
      access_token_prefix: 'access:token:'
      refresh_token_prefix: 'refresh:token:'
      user_token_prefix: 'user:tokens:'
kafka:
  topic-name: EMAIL_SENDING_TASKS