spring:
  application:
    name: task-tracker-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_tracker_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      acks: all
      properties:
        spring:
          json:
            type.mapping: MessageDto:com.walking.backend.domain.dto.kafka.MessageDto
security:
  jwt:
    secret: ${JWT_SECRET}
    access_token_expiration: 30
    refresh_token_expiration: 300
    redis:
      access_token_prefix: 'access:token:'
      refresh_token_prefix: 'refresh:token:'
      user_token_prefix: 'user:tokens:'
    header:
      refresh-token: "X-Refresh-Token"
kafka:
  topic-name: EMAIL_SENDING_TASKS